name: flutterapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BASE
  intl: 0.17.0

  # COMMON
  nb_utils: ^4.4.0

  # FIREBASE PACKAGES
  firebase_auth: ^2.0.0
  firebase_crashlytics: ^2.0.7
  firebase_core: ^1.3.0

  # STATE MANAGEMENT
  mobx: 2.0.1
  flutter_mobx: 2.0.0
  provider: 5.0.0

  # PUSH NOTIFICATION
  onesignal_flutter: 3.0.0-beta3

  # AUTHENTICATION
  google_sign_in: ^5.0.4
  the_apple_sign_in: 1.1.1

  # CONNECTIVITY
  http: 0.13.3

  # ADS
  # admob_flutter: 2.0.0-nullsafety.1

  # VIDEOS
  video_player: ^2.1.10
  chewie: ^1.2.2

  # AUDIO
  # just_audio: ^0.8.0

  # PDF File
  flutter_pdfview: 1.1.0

  # EPUB File
  epub_viewer: ^0.2.2

  # WEB TOOLS
  webview_flutter: ^2.0.9
  html_unescape: 2.0.0

  # IMAGES
  cached_network_image: 3.0.0
  image_picker: ^0.8.1+3

  # SPLASH SCREEN
  splash_screen_view: 3.0.0

  # UI
  cupertino_icons: 1.0.3
  flutter_svg: 0.22.0
  flutter_rating_bar: 4.0.0
  flutter_staggered_grid_view: 0.4.0
  dots_indicator: 2.0.0
  auto_size_text: 3.0.0-nullsafety.0
  otp_text_field: ^1.1.1
  country_code_picker: ^2.0.2
  lottie: ^1.1.0
  flutter_vector_icons: 1.0.0
  flutter_html: ^2.1.0

  # STORAGE
  permission_handler: ^8.1.2

  # LAUNCH URL
  url_launcher: 6.0.3

  # DOWNLOAD
  flutter_downloader: ^1.6.1

  # DATABASE
  sqflite: 2.0.0+3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.0.1+3
  build_runner: ^2.0.5

dependency_overrides:

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - book_loader.json
    - app_loader.json
    - more_data_loader2.json
    - more_data_loader1.json
    - big.jpg
    - get_now_btn.png
    - main_logo.png
    - gift.png
    - trans_logo.png
    - bg.png
    - play_btn.png
    - socialfacebook.png
    - socialgoogle.png
    - error.png
    - noInternet.png
    - epub.png
    - back.png
    - walkimages1.png
    - walkimages2.png
    - walkimages3.png
    - walkimages4.png
    - downloads.png
    - music.png
    - pdf.png
    - video.png
    - default.png
    - logo.png
    - share.png
    - love.png
    - librarysolid.png
    - sunglasses.png
    - vector7.png
    - vector10.png
    - vector12.png
    - vector13.png
    - vector15.png
    - 1.png
    - intersect.png
    - search.png
    - vector8.png
    - backgound.png
    - BookDetails.png
    - bookmark.png
    - bookmark_dark.png
    - chevron.png
    - edit.png
    - eye.png
    - gear.png
    - help.png
    - home-run.png
    - link.png
    - logout.png
    - menu.png
    - next.png
    - pause.png
    - supermarket.png
    - trash.png
    - password.png
    - user.png
    - privacy.png
    - world.png
    - info.png
    - walk_through_bg.png
    - ic_profile.png
    - ic_mode.png
    - verified.png
    - padlock.png
    - ic_CallRing.png
    - ic_Fb.png
    - ic_Inst.png
    - ic_Whatsapp.png
    - ic_Twitter.png
    - login.png
    - lang/en.json
    - lang/fr.json
    - lang/es.json
    - lang/af.json
    - lang/de.json
    - lang/in.json
    - lang/vi.json
    - lang/tr.json
    - lang/hi.json
    - lang/ar.json

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost-Bold.ttf
        - asset: fonts/Jost-Italic.ttf
        - asset: fonts/Jost-Medium.ttf
        - asset: fonts/Jost-Regular.ttf